export const ACCESSIBILITY = {
  PAID_PARKING: 'PAID_PARKING',
  FREE_PARKING: 'FREE_PARKING',
  ENTRANCE_FOR_DISABLED: 'ENTRANCE_FOR_DISABLED',
  WHEELCHAIR_RENTAL: 'WHEELCHAIR_RENTAL',
  DISABLED_TOILET: 'DISABLED_TOILET',
  EXCLUSIVE_PARKING: 'EXCLUSIVE_PARKING',
  LARGE_PARKING: 'LARGE_PARKING',
  GUIDE_DOG_ALLOWED: 'GUIDE_DOG_ALLOWED',
  BRAILLE_GUIDE: 'BRAILLE_GUIDE',
  AUDIO_GUIDE_KR: 'AUDIO_GUIDE_KR',
} as const;
